services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: authorization-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/authorization-service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./migrations:/liquibase/changelog
  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - 8180:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: authorization-service
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: root
    volumes:
      - type: bind
        source: ./keycloak/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
    depends_on:
      - postgresql
    command:
    - start-dev
    - --import-realm
    - --bootstrap-admin-username=admin
    - --bootstrap-admin-password=pass